From us.gcr.io/stackdriver-test-143416/stackdriver-agent-test-container-x86_64_centos8-base:latest
Run dnf -y install https://dev.mysql.com/get/mysql80-community-release-el8-1.noarch.rpm ;\
dnf --disablerepo=AppStream install -y mysql-community-server;
 
CMD ["/usr/sbin/init"]

